name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/branch_1.2.18' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release' ) && format('ci-main-{0}', github.sha) || format('ci-main-{0}', github.ref) }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Test:
    name: JDK ${{ matrix.jdk }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [21]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true
      max-parallel: 4
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 50
    - name: Set up Java ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.jdk }}
    
    - name: Fix POM - Remove missing logback-access module
      run: |
        # Remove the logback-access module reference from parent pom.xml
        if [ -f pom.xml ]; then
          sed -i '/<module>logback-access<\/module>/d' pom.xml
          echo "Removed logback-access module from pom.xml"
        fi
      shell: bash
    
    - name: Install
      # Skip tests during install, build only core and classic modules
      run: mvn -B clean install -DskipTests -pl logback-core,logback-classic
    
    - name: Test
      # Run tests only for the modules we built
      run: mvn -B test -pl logback-core,logback-classic
